
name: Documentation
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # https://stackoverflow.com/a/58008902
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      # check out sources that will be used for autodocs, plus readme
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      # didn't need to change anything here, but had to add sphinx.ext.githubpages
      # to my _config.yml extensions list. that fixes the broken uploads
      - name: Run JupyterBook
        run: |
          jupyter-book build docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


