
name: Documentation
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # https://stackoverflow.com/a/58008902
  docs:
    name: Build Docs
    # needs: [build]
    runs-on: ubuntu-latest
    container:
      image: python:3.6
      volumes:
        - dist:dist
        - public:public
    steps:

      # check out sources that will be used for autodocs, plus readme
      - uses: actions/checkout@v2

      # # download wheel that was build and uploaded in the build step
      # - uses: actions/download-artifact@v1
      #   with:
      #     name: distributions
      #     path: dist

      # didn't need to change anything here, but had to add sphinx.ext.githubpages
      # to my conf.py extensions list. that fixes the broken uploads
      - name: Run JupyterBook
        run: |
          pip install -r docs/requirements.txt
          jupyter-book build docs/

      # # still need to build and set the PAT to get a rebuild on the pages job,
      # # apart from that quite clean and nice 
      # - name: github pages deploy
      #   uses: peaceiris/actions-gh-pages@v2.3.1
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.PAT }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: public

      # # # since gh-pages has a history, this step might no longer be necessary.
      # # - uses: actions/upload-artifact@v1
      # #   with:
      # #     name: documentation
      # #     path: public
